import bcrypt from 'bcryptjs';
const data={
    users:[
        {
            name: 'Nazeef',
            email:'admin@example.com',
            password: bcrypt.hashSync('1234',8),
            isAdmin: true,
        },
        {
            name: 'Shan',
            email:'user@example.com',
            password: bcrypt.hashSync('1234',8),
            isAdmin: false,
        },
    ],
    products:[
        {
            name:'Glass Jyoti',
            category:'Pooja Article',
            image:'/images/p1.jpg',
            price:120,
            countInStock: 10,
            brand:'Brass',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            name:'Diya Lamp',
            category:'Pooja Article',
            image:'/images/p2.jpg',
            price:120,
            countInStock: 20,
            brand:'Brass',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            name:'Silver Thali',
            category:'Pooja Article',
            image:'/images/p3.jpg',
            price:120,
            countInStock: 30,
            brand:'Silver',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            name:'Brass Thali',
            category:'Pooja Article',
            image:'/images/p4.jpg',
            price:120,
            countInStock: 10,
            brand:'Brass',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            name:'Silver Trishul',
            category:'Pooja Article',
            image:'/images/p5.jpg',
            price:120,
            countInStock: 50,
            brand:'Silver',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            name:'Silver Pots',
            category:'Pooja Article',
            image:'/images/p6.jpg',
            price:120,
            countInStock: 50,
            brand:'Silver',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            name:'Brass Thali',
            category:'Pooja Article',
            image:'/images/p8.jpg',
            price:120,
            countInStock: 50,
            brand:'Brass',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
    ],
};
export default data;