const data={
    products:[
        {
            _id:'1',
            name:'Glass Jyoti',
            category:'Pooja Article',
            image:'/images/p1.jpg',
            price:120,
            countInStock: 10,
            brand:'Brass',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            _id:'2',
            name:'Diya Lamp',
            category:'Pooja Article',
            image:'/images/p2.jpg',
            price:120,
            countInStock: 20,
            brand:'Brass',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            _id:'3',
            name:'Silver Thali',
            category:'Pooja Article',
            image:'/images/p3.jpg',
            price:120,
            countInStock: 30,
            brand:'Silver',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            _id:'4',
            name:'Brass Thali',
            category:'Pooja Article',
            image:'/images/p4.jpg',
            price:120,
            countInStock: 10,
            brand:'Brass',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            _id:'5',
            name:'Silver Trishul',
            category:'Pooja Article',
            image:'/images/p5.jpg',
            price:120,
            countInStock: 50,
            brand:'Silver',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
        {
            _id:'6',
            name:'Silver Pots',
            category:'Pooja Article',
            image:'/images/p6.jpg',
            price:120,
            countInStock: 50,
            brand:'Silver',
            rating:4.5,
            numReviews:10,
            descritpion:'high quality product',
        },
    ],
}
export default data;